package main

import (
	"image/png"
	"net/url"
	"os"
	"regexp"
	"strconv"
	"strings"
	"testing"
)

// metaContent returns the content of the single <meta> whose key attribute
// equals key. attr is "property" for og:* (what the Open Graph spec uses) and
// "name" for everything else.
func metaContent(t *testing.T, body, attr, key string) string {
	t.Helper()

	re := regexp.MustCompile(`<meta ` + attr + `="` + regexp.QuoteMeta(key) + `" content="([^"]*)">`)
	match := re.FindStringSubmatch(body)
	if match == nil {
		t.Fatalf("no <meta %s=%q> in the page", attr, key)
	}
	return match[1]
}

// A crawler resolves og:image and og:url against nothing at all, so a relative
// value yields no thumbnail rather than a broken one - the failure is invisible
// unless something asserts on it. Both pages are checked because both render
// the shared "meta" template, and only index.html defines it.
func TestBothPagesCarryAbsoluteOpenGraphTags(t *testing.T) {
	for _, page := range []string{"index.html", "resume.html"} {
		body := renderPage(t, page)

		for _, key := range []string{"og:type", "og:site_name", "og:title", "og:description",
			"og:url", "og:image", "og:image:width", "og:image:height", "og:image:alt"} {
			if metaContent(t, body, "property", key) == "" {
				t.Errorf("%s renders %s with an empty content", page, key)
			}
		}

		for _, key := range []string{"og:url", "og:image"} {
			got := metaContent(t, body, "property", key)
			parsed, err := url.Parse(got)
			if err != nil {
				t.Errorf("%s renders an unparseable %s (%q): %v", page, key, got, err)
				continue
			}
			if !parsed.IsAbs() {
				t.Errorf("%s renders a relative %s (%q); crawlers cannot resolve it", page, key, got)
			}
		}

		// Not Open Graph, and the only tag here read under "name". Without it
		// several readers render a small thumbnail beside the text instead of
		// the full-width card the 1200x630 image is sized for.
		if got := metaContent(t, body, "name", "twitter:card"); got != "summary_large_image" {
			t.Errorf("%s renders twitter:card=%q, want summary_large_image", page, got)
		}
	}
}

// Two pages sharing one og:url would have every share of the resume page unfurl
// as the homepage, which is the kind of thing that looks fine in the markup and
// only shows up once it is posted somewhere.
func TestEachPageDeclaresItsOwnCanonicalURL(t *testing.T) {
	index := metaContent(t, renderPage(t, "index.html"), "property", "og:url")
	resume := metaContent(t, renderPage(t, "resume.html"), "property", "og:url")

	if index == resume {
		t.Fatalf("both pages declare og:url=%q", index)
	}
	if want := siteBaseURL + "/"; index != want {
		t.Errorf("index og:url is %q, want %q", index, want)
	}
	if want := siteBaseURL + "/resume"; resume != want {
		t.Errorf("resume og:url is %q, want %q", resume, want)
	}
}

// The width and height in the markup are a promise to the crawler, and nothing
// connects them to the file: the PNG is generated by `make og-image` from
// dimensions held in the Makefile, so changing the size there and forgetting
// the constants here leaves the page describing an image that no longer exists
// at that size. Readers that trust the declared size to reserve layout space
// then render the card cropped or letterboxed.
//
// Reading the file also catches the simpler failure of og-image.png being
// renamed, deleted, or never committed after an SVG edit.
func TestOGImageFileMatchesTheDeclaredDimensions(t *testing.T) {
	// Tests run with the app directory as their working directory, the same
	// assumption ParseGlob("templates/*.html") already makes.
	path := strings.TrimPrefix(ogImagePath, "/")

	file, err := os.Open(path)
	if err != nil {
		t.Fatalf("og:image points at %s, which the app serves from disk: %v", ogImagePath, err)
	}
	defer file.Close()

	// Also asserts the file really is a PNG; a crawler will not guess.
	config, err := png.DecodeConfig(file)
	if err != nil {
		t.Fatalf("%s is not a decodable PNG: %v", path, err)
	}

	wantWidth, err := strconv.Atoi(ogImageWidth)
	if err != nil {
		t.Fatalf("ogImageWidth %q is not a number: %v", ogImageWidth, err)
	}
	wantHeight, err := strconv.Atoi(ogImageHeight)
	if err != nil {
		t.Fatalf("ogImageHeight %q is not a number: %v", ogImageHeight, err)
	}

	if config.Width != wantWidth || config.Height != wantHeight {
		t.Errorf("%s is %dx%d, but the page declares %sx%s - regenerate with `make og-image` "+
			"or update the constants in handlers.go",
			path, config.Width, config.Height, ogImageWidth, ogImageHeight)
	}
}
