apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resume-site
  namespace: resume-site
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - robertjcameron.com
      secretName: resume-site-tls
  rules:
    - host: robertjcameron.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: resume-site
                port:
                  number: 80
